# Generated by Django 6.0.2 on 2026-03-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_country_city_country_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
